### ISSUE TITLE
Change in source data: some column names missing

### ISSUE THREAD

**Issue by jebyrnes** [debusklaneml/CanadaC19#4]
The following names were missing in the 2020-04-27 21:11:06 refresh of CanadaC19:

```value```

**Comment by debusklaneml** [comment]
Added in a value column.

**Comment by aedobbyn** [comment]
Sorry about all these issues! We have a GitHub Action set up to run this on a schedule.

Using the version on master from GitHub, not seeing a `value` column. @jebyrnes if you run this locally do you see `value`?

Weird because it looks like you add it [here](https://github.com/debusklaneml/CanadaC19/blob/master/R/utils.R#L62-L64) @debusklaneml

**Comment by jebyrnes** [comment]
Just installed it from github and, indeed, it's there.

``` r
#remotes::install_github("debusklaneml/CanadaC19")
library(CanadaC19)

n_canada <- refresh_CanadaC19_cases() %>% names()
#> Downloading raw data from https://raw.githubusercontent.com/ishaberry/Covid19Canada/master/cases.csv.
"value" %in% n_canada
#> [1] TRUE

n_canada
#>  [1] "case_id"                "provincial_case_id"     "date"                  
#>  [4] "location"               "location_type"          "data_type"             
#>  [7] "travel_yn"              "locally_acquired"       "data_details"          
#> [10] "data_url"               "additional_info"        "travel_history_country"
#> [13] "age"                    "sex"                    "location_code"         
#> [16] "location_code_type"     "value"
```

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by debusklaneml** [comment]
Is there anything I need to do to push this change to covid19r's master? Or is this something you guys need to do for changes on your end? @aedobbyn @jebyrnes

**Comment by aedobbyn** [comment]
Weirdly it was there for me in a reprex too but not in an interactive session. Not sure why that is.

@debusklaneml I don't think you need to do anything -- since `value` apparently is there I think this isn't an actual bug. We can take your package out of our GitHub Action flow if the Issues are annoying

**Comment by debusklaneml** [comment]
In building out some of the standardized variables I initially forgot, one being 'value,' I noticed I did not include them as globals. This may have contributed to the problem.

**Comment by aedobbyn** [comment]
Seeing it now, thanks for fixing!
